### ISSUE TITLE
Expose C interface

### ISSUE THREAD

**Issue by ariddell** [sakrejda/protostan#11]
Do we need to drop the namespaces for the shim to be usable from programming languages that only wrap C functions? Will everything need to be declared `extern "C"` or should the shim library be written in C?

**Comment by ariddell** [comment]
This looks very helpful: https://isocpp.org/wiki/faq/mixing-c-and-cpp

**Comment by ariddell** [comment]
This might have to wait until there's a C library supporting protobuf version 3.

**Comment by sakrejda** [comment]
Looks like.  I'm going to close for now, I think we can come up with a better first project.
