### ISSUE TITLE
Replace 'stanc' with 'compile'

### ISSUE THREAD

**Issue by ariddell** [sakrejda/protostan#18]
'stanc' is a cmdstan-ism. Using `compile` everywhere (incl. filenames) is clearer.

**Comment by ariddell** [comment]
This is a bit more involved than I thought. We need to compile protostan's tests without relying on Stan's makefile. In principle people using protostan will be working with a different Stan tree and will not have libstan.a on hand (I think this is right).

**Comment by sakrejda** [comment]
Could you explain why this is tied up with Stan's makefile?  I don't see the connection to not using 
"stanc" as a name.

**Comment by ariddell** [comment]
There's a rule in the Makefile which uses libstanc.a -- I'm pretty sure this is an artifact which is there for cmdstan from the days when cmdstan was part of the stan repo. I may be wrong about this.

**Comment by sakrejda** [comment]
I thought PyStan would also need to do the compilation required to make something like libstanc.a, no?  Do you really recompile everything for every model?

**Comment by ariddell** [comment]
PyStan compiles a hybrid Python/C++ thing for compilation separately.
When models are compiled they don't need to use the stan/lang stuff.

For testing I think it makes sense to leave libstanc.a the way it is.
But I do think it's a good idea to replace 'stanc' with 'compile'
elsewhere. That's the function signature after all. Without knowledge of
cmdstan I think 'stanc' doesn't have a clear reference.

**Comment by sakrejda** [comment]
Ok, works for me.  I can take care of it, I think there's some proto
file/c++ namespace issue involved.

**Comment by ariddell** [comment]
I've got a PR ready, let me send that.

**Comment by sakrejda** [comment]
Ok
