### ISSUE TITLE
Makefile should assume user has protoc in path

### ISSUE THREAD

**Issue by ariddell** [sakrejda/protostan#27]
Currently the Makefile forces the user to use the included protoc which isn't ideal. The default case will be that the user already has protoc installed (via their operating system package manager).

**Comment by ariddell** [comment]
This is the last thing to cleanup before pystan-protostan will be tested via travis.

**Comment by sakrejda** [comment]
I don't think this is a good idea unless there's a way to make it
possible/easy to use either.  proto2 is still the default and at least the
Ubuntu builds didn't include proto3 last I checked.

**Comment by ariddell** [comment]
I don't think any mature packages (<1% for sure) ship an external tool like protobuf with the package. It would be like packaging the Rcpp source with RStan.

In the short term I think we just need to fix the Makefile so that the user isn't forced to use the protobuf 3 that's a submodule. I'll figure this out. It's just a shell check or two.

**Comment by sakrejda** [comment]
Agreed, at this point this is hardly a mature package although I know
that's a consideration for perching pystan on top of it.  If you see a way
of doing it so that it's easy to switch go for it.  I'm still in the middle
of traveling so I won't get to any Stan stuff till sometime next week.

**Comment by ariddell** [comment]
I think this isn't an issue for the present Makefile (which is intended to help us run tests).
