### ISSUE TITLE
Add .proto spec. for output format

### ISSUE THREAD

**Issue by sakrejda** [sakrejda/protostan#29]
- [x] add protobuf spec to match writer API
  - [X] iteration
  - [X] errors
  - [X] diagnostic info

**Comment by sakrejda** [comment]
@ariddell The easiest writer for me to write would just dump delimited output to a file (as in binary with a specific format).  Is there something else I should do? Is there a Python-compatible FIFO or something like that? I guess I could also output JSON just as an intermediary.

**Comment by ariddell** [comment]
How about jsonlines, http://jsonlines.org/ -- it's just newline delimited json. Will that work?

**Comment by sakrejda** [comment]
Sure, that's the easiest thing you could've picked.

**Comment by sakrejda** [comment]
Modified to-do, the writer spec had me confused---you need multiple writers with protobuf because the goal is to formalize a little, rather than just dump text into protobuf wholesale.

**Comment by sakrejda** [comment]
Writers (real there are multiple for different purposes) are a separate issue.
