### ISSUE TITLE
First writer

### ISSUE THREAD

**Issue by sakrejda** [sakrejda/protostan#35]
To check on how much CPU is chewed up going from Eigen data types to Protocol Buffers in practice, do a simple writer which:
- [ ] constructs the correct protocol buffers messages
- [ ] converts to JSON
- [ ] writes messages in newline delimited JSON to a file.
  This should be a drop-in replacement for stream_writer for output, so 
- [ ] fork/hack CmdStan a little to do a comparison of this versus .csv output (which also has to convert to text).

**Comment by sakrejda** [comment]
First time reading too fast bites: turns out protobuf-to-JSON is NOT native in the C++ version of the library.  Not sure how I got that wrong.  Needs different strategy, likely just deal with binary serialization and then look at how practical it is to read these from an higher-level interface (R/Python).

**Comment by ariddell** [comment]
protobuf3 to json will be in the C++ version. I think it might be there already somewhere but perhaps not documented. You see mentions of it in the changelog: https://github.com/google/protobuf/blob/4ab918674368e237e1cf6be467c1c4223dd2b510/CHANGES.txt

Here's the spec:
- https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by ariddell** [comment]
What will not be in protobuf3 is json->protobuf. Will this be a problem?

**Comment by sakrejda** [comment]
Only for doing JSON input into a CmdStan fork. I'll do the writer anyway and we can see where things go form there.  Do you know if they've declared that's "beyond scope" or if it's just a "we'll do it later"? I'm pretty sure there is a JSON parser in the tree now (your comment prodded me to dig through their code some more).

**Comment by ariddell** [comment]
I'm sure a 3rd party will do the json->protobuf eventually. I think there's such a thing already for protobuf2

**Comment by sakrejda** [comment]
The PB -> JSON functionality is still buried in a utility that needs a bunch of internal protobuf arguments to run the PB -> JSON conversion function.  I'm going to wait on this until they release a cleaner API.  In the meantime we can deal with binary protobuf messages all the way to the client.  If you're curious it's in:

```
protostan/lib/protobuf/src/google/protobuf/util/json_util.h
```

**Comment by ariddell** [comment]
This sounds like a solid plan.

**Comment by ariddell** [comment]
There's a new release of protobuf which looks like it has improved JSON support https://github.com/google/protobuf/releases
