### ISSUE TITLE
Figure out namespaces

### ISSUE THREAD

**Issue by sakrejda** [sakrejda/protostan#36]
Looks like:
- [ ] stan::proto should be where the message types live, we got this right.
- [ ] stan::interface_callbacks::writer is where the new writers should go, even though internally they do some protobuf stuff, they're still writers and should live with all the writers.
- [ ] stan::proto::compile is in stan::proto, rather than stan::lang, even though it's a "compile"

Looks like we are exposing three types of things: 1) messages; 2) thin wrappers; and 3) callbacks.  So generalizing to a namespace policy:
- If it's a message it lives in stan::proto
- If it's takes message arguments and returns messages, it's part of the thin wrapper and should also live in stan::proto
- If it's a callback it's implementing additional logic and not necessarily dealing with protobuf types as function inputs/outputs so it goes in whatever namespace that type of callback usually goes.

@ariddell Feel free to comment, close if you agree and I'll write it up as a Wiki thing and/or add to README.md

**Comment by ariddell** [comment]
I don't know the C++ convention here. Does one try to keep an external package in its own namespace? For example, what if by accident we end up clobbering a function name (say, 'compile') in stan::lang with the protostan version?

**Comment by sakrejda** [comment]
That should only be an issue for callbacks in the scheme outlined above and there... I don't know. At least callbacks are pretty job-specific and tend to have less common names (and more specialized purposes) so I don't see this being a big issue.

**Comment by ariddell** [comment]
Anyway, this all sounds good.
