### ISSUE TITLE
Remove protobuf source from repository (or whatever is making cloning slow)

### ISSUE THREAD

**Issue by ariddell** [sakrejda/protostan#39]
Protostan should be very fast to clone (without submodules). Not sure how best to fix this. It should be fixed though.

**Comment by sakrejda** [comment]
The git call for removing everything matching PATTERN is something like: 

```
git filter-branch --force --index-filter \
    'git rm --cached --ignore-unmatch PATTERN' \
      --prune-empty --tag-name-filter cat -- --all
```

There's another snippet that you can call to get a sorted list of big objects/etc.... so it takes a little while to figure out what's responsible.  I can look into it in a few days if you don't get to it...

**Comment by sakrejda** [comment]
It'll screw up branches but I think the changes can be done on develop and merged back into branches.  It's not like we have a lot of people using this at the moment.

**Comment by ariddell** [comment]
I think it'll speed up testing a lot. I wouldn't mind if you just reset history after you merge your branches.

**Comment by sakrejda** [comment]
I did this locally and I think I got it right... it's surprisingly hard to flush out all the packed files.

**Comment by ariddell** [comment]
ok! Feel free to force push.

**Comment by sakrejda** [comment]
I'm going to finish the writers branch before I do this. Working on it now...

**Comment by sakrejda** [comment]
Done.
