### ISSUE TITLE
Add a binaryProtubufFileWriter

### ISSUE THREAD

**Issue by sakrejda** [sakrejda/protostan#43]
- [x] Choose hierarchy
- [x] Refactor stream writer
- [x] Add writer that has a filename constructor (open used internally to get fd) 
- [x] Modify tests for file-based writer.

**Comment by ariddell** [comment]
Who's the target audience for this (i.e., the file writer)? Is it just for testing?

**Comment by sakrejda** [comment]
It's an easy split do do, matches the available implementations from protobuf (OstreamOutputStream and FileOutputStream), and it will make it dead simple to integrate this into a full CmdStan, so I guess the target audience is a fork/hack on CmdStan to demonstrate/tune it as an easy binary output format.

**Comment by ariddell** [comment]
Is there an argument in favor of this being cmdstan's responsibility? I mean, would servestan use this?

(You can see I'm zealot for avoiding any code bloat.)

**Comment by sakrejda** [comment]
Sure there could be, but what I want is a demo to show that a) having
protobuf as a dependency is not going to cause a big headache for CmdStan;
and b) we can produce a good binary format through this route.

If there's going to be a binary format I'd like to have a go at it being
protobuf-based so that it's uniform across interfaces so I'm willing to put
in a little extra work to have a demo for it.  Ultimately I guess ServeStan
(Andrew/Daniel have been calling this idea CloudStan, which is fun) could
use this if there's going to be any caching of results/models/etc.

I agree about avoiding code bloat but I don't think this is it.  Also,
until we make a commitment to support sub-projects (interfaces) we have
free reign to lop off things that don't work out!

**Comment by ariddell** [comment]
What about putting that in something else, like cmdstan-protostan?

I'm just thinking here about eventually getting PyStan 3 running on this and I'd love for it to be as clean and focused as possible.

**Comment by ariddell** [comment]
I'll note that https://github.com/ariddell/cmdstan-protostan is basically working. It would be easy to add the file writer there and would be easier, I think, for others to grasp the demo.

I feel like our next step should be to have some data that's worth writing! i.e., get a model up and running and producing samples, streamed over the deliminted pb writer.

**Comment by ariddell** [comment]
This sounds fine but I think it would be great to separate out these things into separate projects. I always thought there would be a library (called "protostan" but perhaps something else) which would just be the set of .proto files and a _tiny_ set of cpp files which would be usable (in theory) by RStan, PyStan, ServeStan, and CmdStan.

For example, some features that are useful to cmdstan may not be useful to RStan, PyStan, and ServeStan. Parsing command-line arguments, for example. Or file input/output. Perhaps these could go in a separate project that has Stan and protostan (or "protostan-lib", if you want to rename it) as dependencies?

**Comment by ariddell** [comment]
It sounds like we're on the same page.

re: the writer -- I think everyone would need the pb_delimited writer --- or something very much like it, right? I could have this wrong. I'll know more as I read through the new code.

**Comment by sakrejda** [comment]
I ripped out all the explicit calls to a write_delimited_pb and replaced them with a function pointer template argument so the same class can now do multiple stream types (anything subclassed from ZeroCopyStream) and it'll be easy to write a write_jsonlines_pb stand-alone function to pass in as a template argument when protobuf comes around to implementing that feature.  Feels a little over-engineered but it's much less code this way, I wrote new test for OstreamOutputStream and FileOutputStream and it all works nicely... open to thoughts about the data format/overengineered aspect but I'm calling this issue done.

**Comment by ariddell** [comment]
OK. I think this looks good. Looking forward to working through it (and any docs #42).

**Comment by sakrejda** [comment]
Added the docs this morning, moved cleanup to a separate issue because
[soccer analogy]. K
