### ISSUE TITLE
Use gRPC

### ISSUE THREAD

**Issue by arthur-tacca** [sakrejda/protostan#56]
This project would be more useful if it used [gRPC](http://www.grpc.io/) as the serialisation / message handling layer instead of the manual length-prefixed serialisation code it currently uses. The change would not be that fundamental, as gRPC is also based on Protocol Buffers.

Benefits:

 * It would mean (a little) less code in this project to do the message delimiting stuff.
 * It would mean less code in the *client* to do the message delimiting stuff. I think I read somewhere about a plan to make C++ wrapper functions to help with this, but gRPC is language indepedent, like protocol buffers, so this would work for more types of client. Of course the length prefixing stuff is not really that big of a deal but a nice interface doesn't hurt. 
 * It would also help with the maximum proto issue: You can use a streaming request to send multiple protobufs for a single request. Search for "client-side streaming RPC" in the [gRPC C++ introdction](http://www.grpc.io/docs/tutorials/basic/c.html).
 * Other gRPC goodies would become possible (although they are probably not that useful for this project) e.g. SSL, load balancing (when it comes), request multiplexing...

**Comment by arthur-tacca** [comment]
Sorry. Immediately after posting this issue I had a further look around the repo and noticed `compile-grpc.proto`, so you're already at least considering this. I would delete this issue if I could but I don't seem to have that option, so I'll just close it instead.

**Comment by sakrejda** [comment]
Thanks for taking a look.  I've been messing around with this mostly to have a good sense of what it would look like if implemented for real.  There's another repo on my account somewhere that does a little server using gRPC.  I think long term it will be a good idea but for the moment there's a lot of movement internally in Stan sorting out I/O and related format issues so it would be a lot of work to develop this and track the changes coming in Stan.  Feel free to get in touch directly if expanding this project is relevant to you.
