### ISSUE TITLE
Setup cpplint CI test

### ISSUE THREAD

**Issue by ariddell** [sakrejda/protostan#7]
cpplint: https://github.com/google/styleguide/tree/gh-pages/cpplint

I think this isn't difficult to do. Perhaps Stan has done this already?

**Comment by sakrejda** [comment]
For now I think we can do this locally.  In general I do make test before I commit anything to develop and adding cpplint to that workflow sounds useful.  CI seems like too much infrastructure for now (?)
- [x] Add cpplint on all hand-coded cpp files to makefile (maybe "make test" for cpplint + gtest, "make gtest" for the c++ tests and "make lint" for cpplint(?)
- [x] Grab/use Stan's options for running cpplint---there was a discussion about this on stan-dev and Daniel listed the options that run on Stan.  They're also in the code.

**Comment by sakrejda** [comment]
cpplint tests passed locally and on travis, closing, I'll wait to merge till the whole CI thing is done.
